name: alicia
description: Alicia - Gestor Contenido.
#flutter config --enable-windows-desktop
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crop_your_image: ^0.5.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  expandable: ^5.0.1
  filepicker_windows: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_treeview: ^1.0.3+2
  flutter_widget_from_html_core: ^0.6.1+1
  font_awesome_flutter: ^9.0.0
  http: any
  image: ^3.0.2
  intl: ^0.17.0
  mysql1: ^0.19.2
  provider: ^5.0.0
  responsive: ^0.3.9+9
  screenshot: ^0.3.0
  searchable_dropdown: ^1.1.3
  sortedmap: ^0.5.0
  web_pagination: ^0.0.3
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Century Gothic
      fonts:
        - asset: fonts/GOTHIC.ttf
        - asset: fonts/GOTHICI.ttf
          style: italic
        - asset: fonts/GOTHICB.ttf
          weight: 700
        - asset: fonts/GOTHICBI.ttf
          style: italic
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
